apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: baz-tls
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: baz-cert-tls
      namespace: default
    sniDomains:
      - baz.34.69.182.150.nip.io
  virtualHost:
    domains:
    - baz.34.69.182.150.nip.io
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system

