apiVersion: gloo.solo.io/v1
kind: UpstreamGroup
metadata:
  name: my-service-group
  namespace: gloo-system
spec:
  destinations:
  - destination:
      upstream:
        name: default-petstore-8080
        namespace: gloo-system
    weight: 9
  - destination:
      upstream:
        name: default-petstore-8080
        namespace: gloo-system
    weight: 1

