{{- if .Values.global.glooMtls.enabled }}
---
# config_map
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-sidecar-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: gloo
    gloo: gloo
data:
  envoy-sidecar.yaml: |
    node:
      id: sds_client
      cluster: sds_client
    static_resources:
      listeners:
      - name: envoy_mtls_listener
        address: { socket_address: { address: "0.0.0.0", port_value: {{ .Values.gloo.deployment.xdsPort }} } }
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: gloo_cluster
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                  - name: server_cert
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                        - envoy_grpc:
                            cluster_name: gloo_sds
                validation_context_sds_secret_config:
                  name: validation_context
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                      - envoy_grpc:
                          cluster_name: gloo_sds
      clusters:
      - name: gloo_sds
        connect_timeout: 0.25s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: gloo_sds
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8234
      - name: gloo_cluster
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: gloo_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9999
        http2_protocol_options: {}
        type: STRICT_DNS
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
{{- end}}