{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: {{ $.Release.Namespace }}
{{- if .Values.gateway.proxyServiceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}

{{ end }}