apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: quay.io/sololabs/petclinic:v3
        env:
        - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
          value: "true"
        - name: SERVER_TOMCAT_ACCESSLOG_DIRECTORY
          value: /dev
        - name: SERVER_TOMCAT_ACCESSLOG_PREFIX
          value: stdout
        - name: SERVER_TOMCAT_ACCESSLOG_BUFFERED
          value: "false"
        - name: SERVER_TOMCAT_ACCESSLOG_SUFFIX
        - name: SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT
        - name: SERVER_TOMCAT_ACCESSLOG_PATTERN
          value: '[ACCESS] %{org.apache.catalina.AccessLog.RemoteAddr}r %l %t %D %F
            %B %S vcap_request_id:%{X-Vcap-Request-Id}i Matched-Allowed-Headers:%{Matched-Allowed-Headers}i'
            # docs for access logs: https://tomcat.apache.org/tomcat-8.5-doc/config/valve.html#Access_Log_Valve
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: petclinic
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petclinic-db
  labels:
    app: petclinic-db
spec:
  selector:
    matchLabels:
      app: petclinic-db
  serviceName: petclinic-db
  template:
    metadata:
      labels:
        app: petclinic-db
    spec:
      containers:
      - name: petclinic-db
        image: quay.io/sololabs/petclinic-db:v3
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "petclinic"
        - name: MYSQL_DATABASE
          value: "petclinic"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: sql-data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: sql-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
  labels:
    app: petclinic-db
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: petclinic-db
  type: ClusterIP
