global:
  extensions:
    dataplanePerProxy: true
gloo:
  gatewayProxies:
    gatewayProxy:
      disabled: true
    internalProxy:
      gatewaySettings:
        customHttpGateway:
          options:
            extauth:
              extauthzServerRef:
                name: extauth-internal-proxy
                namespace: gloo-system
            ratelimitServer:
              ratelimitServerRef:
                name: rate-limit-internal-proxy
                namespace: gloo-system
          virtualServiceSelector:
            gateway-type: internal

