apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: allow-users-opa
  namespace: gloo-system
spec:
  configs:
  - opa_auth:
      modules:
      - name: allow-users
        namespace: gloo-system
      query: "data.test.allow == true"

