{{- if .Values.rateLimit.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.redis.service.name }}
  name: {{ .Values.redis.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      protocol: TCP
  selector:
    gloo: {{ .Values.redis.service.name }}
{{- end }}