{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}

{{- if $extAuth.envoySidecar }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.service.name }}
  name: {{ $extAuth.service.name }}-sidecar
  namespace: {{ .Release.Namespace }}
spec:
  use_http2: true
  pipe:
    path: "/usr/share/shared-data/.sock"
{{- end }}
---
{{- if $extAuth.standaloneDeployment }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.service.name }}
  name: {{ $extAuth.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  use_http2: true
  healthChecks:
  - timeout: 5s
    interval: 10s
    unhealthyThreshold: 3
    healthyThreshold: 3
    grpcHealthCheck:
      serviceName: {{ $extAuth.serviceName }}
  kube:
    serviceName: {{ $extAuth.service.name }}
    serviceNamespace: {{ .Release.Namespace }}
    servicePort:  {{ $extAuth.service.port }}
    serviceSpec:
      grpc: {}
  {{- if .Values.global.glooMtls.enabled }}
  sslConfig:
    secretRef:
      name: gloo-mtls-certs
      namespace: gloo-system
  {{- end }}
{{- end }}
{{- end }}
