{{- if .Values.rateLimit.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.rateLimit.service.name }}
  name: {{ .Values.rateLimit.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.rateLimit.service.port }}
    protocol: TCP
  selector:
    gloo: {{ .Values.rateLimit.service.name }}
{{- end }}