{{- if .Values.apiServer.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: {{ .Values.apiServer.service.name }}
  annotations:
    gloo.solo.io/h2_service: "true"
spec:
  ports:
    - name: static
      port: {{.Values.apiServer.deployment.ui.staticPort}}
      protocol: TCP
  selector:
    gloo: {{ .Values.apiServer.service.name }}
  type: ClusterIP
{{- end }} # .Values.apiServer.enable
