{{- if .Values.rateLimit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.rateLimit.service.name }}
  name: {{ .Values.rateLimit.service.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
