{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability
  namespace: {{ $.Release.Namespace }}
{{- end }}