gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        httpsPort: 8080
      service:
        extraAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:410461945957:certificate/52a75a75-ab2c-42ed-b7d8-2176fa41bda4
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        httpsFirst: true

