apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes-3
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /foo/bar
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system

