apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes-foo
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /foo
    directResponseAction:
      status: 200
      body: "Hello, world!"

