apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-route
  namespace: default
spec:
  routes:
  - matchers:
    - prefix: /
      headers:
      - name: x-foo
        value: bar
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system

