apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      transformations:
        requestTransformation:
          transformationTemplate:
            extractors:
              pathGroupOne:
                header: :path
                regex: ^\/([^\/]*)\/.*$
                subgroup: 1
              pathGroupTwo:
                header: :path
                regex: ^\/[^\/]*\/(.*)$
                subgroup: 1
            headers:
              ":path":
                text: '/{{ pathGroupOne }}.{{ header(":authority") }}/{{ pathGroupTwo }}'
            passthrough: {}
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system

