gloo:
  gatewayProxies:
    gatewayProxy:
      tracing:
        provider:
          name: envoy.tracers.zipkin
          typed_config:
            "@type": "type.googleapis.com/envoy.config.trace.v2.ZipkinConfig"
            collector_cluster: zipkin
            collector_endpoint: "/api/v2/spans"
            collector_endpoint_version: HTTP_JSON
        cluster:
          - name: zipkin
            connect_timeout: 1s
            type: STRICT_DNS
            load_assignment:
              cluster_name: zipkin
              endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: zipkin.default.svc.cluster.local
                        port_value: 9411

