admin:
  existingSecret: ""
  passwordKey: admin-password
  userKey: admin-user
adminUser: admin
affinity: {}
dashboardProviders: {}
dashboards: {}
dashboardsConfigMaps: {}
datasources: {}
deploymentStrategy:
  type: RollingUpdate
downloadDashboards:
  env: {}
downloadDashboardsImage:
  pullPolicy: IfNotPresent
  repository: curlimages/curl
  tag: 7.68.0
env: {}
envFromSecret: ""
envRenderSecret: {}
envValueFrom: {}
extraConfigmapMounts: []
extraContainers: ""
extraEmptyDirMounts: []
extraExposePorts: []
extraInitContainers: []
extraSecretMounts: []
extraVolumeMounts: []
grafana.ini:
  analytics:
    check_for_updates: true
  grafana_net:
    url: https://grafana.net
  log:
    mode: console
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
image:
  pullPolicy: IfNotPresent
  repository: grafana/grafana
  tag: 6.6.2
ingress:
  annotations: {}
  enabled: false
  extraPaths: []
  hosts:
  - chart-example.local
  labels: {}
  path: /
  tls: []
initChownData:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: busybox
    tag: 1.31.1
  resources: {}
ldap:
  config: ""
  enabled: false
  existingSecret: ""
livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
namespaceOverride: ""
nodeSelector: {}
notifiers: {}
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: false
  finalizers:
  - kubernetes.io/pvc-protection
  size: 10Gi
  type: pvc
plugins: []
podDisruptionBudget: {}
podPortName: grafana
rbac:
  create: true
  extraClusterRoleRules: []
  extraRoleRules: []
  namespaced: false
  pspEnabled: true
  pspUseAppArmor: true
readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
replicas: 1
resources: {}
securityContext:
  fsGroup: 472
  runAsUser: 472
service:
  annotations: {}
  labels: {}
  port: 80
  portName: service
  targetPort: 3000
  type: ClusterIP
serviceAccount:
  create: true
  name: null
  nameTest: null
sidecar:
  dashboards:
    SCProvider: true
    defaultFolderName: null
    enabled: false
    folder: /tmp/dashboards
    label: grafana_dashboard
    provider:
      allowUiUpdates: false
      disableDelete: false
      folder: ""
      name: sidecarProvider
      orgid: 1
      type: file
    searchNamespace: null
  datasources:
    enabled: false
    label: grafana_datasource
    searchNamespace: null
  image: kiwigrid/k8s-sidecar:0.1.99
  imagePullPolicy: IfNotPresent
  resources: {}
smtp:
  existingSecret: ""
  passwordKey: password
  userKey: user
testFramework:
  enabled: true
  image: bats/bats
  securityContext: {}
  tag: v1.1.0
tolerations: []
