apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nip-io
  namespace: default
spec:
  secretName: nip-io-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: 34.71.12.226.nip.io
  dnsNames:
    - 34.71.12.226.nip.io

