apiVersion: v1
data:
  apiKey: YXBpS2V5OiBZMkkxWkRGaVkyRXRPV0k1TkMwMU16bG1MV1l4TlRJdFpEYzJObU5qTmpnNVpqTmgKZ2VuZXJhdGVBcGlLZXk6IHRydWUKbGFiZWxzOgotIHRlYW09aW5mcmFzdHJ1Y3R1cmUK
kind: Secret
metadata:
  annotations:
    resource_kind: '*v1.Secret'
  labels:
    team: infrastructure
  name: petstore-apikey
  namespace: gloo-system
type: Opaque
