apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: apikey-auth-two
  namespace: gloo-system
spec:
  configs:
  - api_key_auth:
      label_selector:
        team: infrastructure
