
# Rbac manifests for dev-portal

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-portal
  labels:
    app: dev-portal
rules:
- apiGroups:
  - devportal.solo.io
  resources:
  - portals
  - apidocs
  - users
  - groups
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - devportal.solo.io
  resources:
  - portals/status
  - apidocs/status
  - users/status
  - groups/status
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-portal
  labels:
    app: dev-portal
subjects:
- kind: ServiceAccount
  name: dev-portal
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dev-portal
  apiGroup: rbac.authorization.k8s.io