apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: external-podinfo
  namespace: external-app
spec:
  kube:
    serviceName: podinfo
    serviceNamespace: external-app
    servicePort: 9898
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: external-podinfo
  namespace: external-app
  labels:
    env: external
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: external-podinfo
            namespace: external-app

